RspecとFactoryBotを導入する
Progaku-copy/progaku-archive pull request #11
Opened 2023-10-01 01:20 UTC by Kaito1290

## 対応するissue
- #4

## 対応内容
- RSpecを導入しました。

## 導入手順
`docs/backend/rspec.md`をご覧ください。

2023-10-01 01:25 UTC, Kaito1290 commented
FactoyBotの導入も作業完了次第pushします！

2023-10-01 04:35 UTC, ochi-sho-private-study commented
@Kaito1290 
一応RspecとFactoryBotの動作確認用に、Userモデルのemailに関してバリデーションのテストを書いてほしいです〜 🙏 
以下のPRがマージされたらこの差分を取り込むといいかと思います！
https://github.com/Progaku-copy/progaku-archive/pull/9

2023-10-01 14:21 UTC, Kaito1290 commented
> @Kaito1290 一応RspecとFactoryBotの動作確認用に、Userモデルのemailに関してバリデーションのテストを書いてほしいです〜 🙏 以下のPRがマージされたらこの差分を取り込むといいかと思います！
> 
> * [Ridgepoleを導入する #9](https://github.com/Progaku-copy/progaku-archive/pull/9)

@ochi-sho-private-study 
下記コミットでFactoryBotとRSpecの導入と動作確認についてのドキュメント作成しました！
レビューお願いします 🙏
https://github.com/Progaku-copy/progaku-archive/pull/11/commits/b67a69efc0f3b06c9417ff38f4cf52e29537378c

2023-10-01 15:56 UTC, ochi-sho-private-study commented on backend/.rspec
> +--require spec_helper
rails_helper.rbにspec_helperをrequireしているので、
`--require rails_helper`さえ書けばよさそうです〜

```suggestion
--require rails_helper
```

2023-10-01 15:59 UTC, ochi-sho-private-study requested changes
@Kaito1290 
コメントしました〜 🙏

2023-10-01 15:59 UTC, ochi-sho-private-study commented on backend/db/migrate/20231001132321_create_users.rb
以下のPRの差分を取り込んで、Ridgepoleを使用するようにしてもらえますか〜？ 🙏 

- https://github.com/Progaku-copy/progaku-archive/pull/9

2023-10-02 14:26 UTC, Kaito1290 commented on backend/.rspec
> +--require spec_helper
下記コミットで修正しました！
https://github.com/Progaku-copy/progaku-archive/pull/11/commits/e5c4c444fbc96ba5aa80c9835e3c18a9350af0b8

2023-10-02 14:29 UTC, Kaito1290 commented on backend/db/migrate/20231001132321_create_users.rb
差分の取り込みと、RSpecの修正を行いました！
確認お願いいたします🙏

2023-10-07 10:05 UTC, ochi-sho-private-study requested changes
@Kaito1290 
コメントしました〜 🙏

2023-10-07 10:05 UTC, ochi-sho-private-study commented on docs/backend/Rspec_FactoryBot.md
> +- 参考記事
FYI

以下のように記述すると、リンクがつくかと思います〜
```suggestion
- [RSpecとFactoryBotの動作確認](#RSpecとFactoryBotの動作確認)
- [RSpecについて](#RSpecについて)
- [FactoryBotについて](#FactoryBotについて)
- [参考記事](#参考記事)
```

2023-10-07 10:05 UTC, ochi-sho-private-study commented on docs/backend/Rspec_FactoryBot.md
> +  ```
`config.include FactoryBot::Syntax::Methods`を記述しているので、
FactoryBotクラスを明示する必要がないことを書いておいた方が良いかと思います〜

2023-10-07 10:05 UTC, ochi-sho-private-study commented on docs/backend/Rspec_FactoryBot.md
> +bundle exec  rspec spec/system/users_spec.rb:10
余分なスペースが入っています〜
```suggestion
bundle exec rspec spec/system/users_spec.rb:10
```

2023-10-07 10:05 UTC, ochi-sho-private-study commented on backend/spec/models/user_spec.rb
> +  it "is valid with valid attributes" do
IMO

これはチームの方針によるのですが、文言は日本語で書いたほうがわかりやすいかと思いました〜

2023-10-07 14:28 UTC, Kaito1290 commented on backend/Gemfile
> +  gem 'rspec-rails' # RSpecのgem
下記コミットで修正しました！
https://github.com/Progaku-copy/progaku-archive/pull/11/commits/cab80fb28a8b6990916978cb4fbdad0f29aacac0

2023-10-07 14:29 UTC, Kaito1290 commented on docs/backend/Rspec_FactoryBot.md
> +- 参考記事
下記コミットで修正しました！
https://github.com/Progaku-copy/progaku-archive/pull/11/commits/4c4d15a6ec2e3408510b40c3b2ea6609a6849df2

2023-10-07 14:31 UTC, Kaito1290 commented on docs/backend/Rspec_FactoryBot.md
> +  ```
下記コミットで修正しました！
https://github.com/Progaku-copy/progaku-archive/pull/11/commits/cab80fb28a8b6990916978cb4fbdad0f29aacac0

2023-10-07 14:31 UTC, Kaito1290 commented on docs/backend/Rspec_FactoryBot.md
> +bundle exec  rspec spec/system/users_spec.rb:10
下記コミットで修正しました！
https://github.com/Progaku-copy/progaku-archive/pull/11/commits/cab80fb28a8b6990916978cb4fbdad0f29aacac0

2023-10-07 14:32 UTC, Kaito1290 commented on backend/spec/models/user_spec.rb
> +  it "is valid with valid attributes" do
下記コミットで修正しました！
https://github.com/Progaku-copy/progaku-archive/pull/11/commits/be5467d235db7ca9d694fb54c8006cdebfba8dad

2023-10-08 03:34 UTC, ochi-sho-private-study approved these changes
@Kaito1290 
LGTMです！
最後にとくゆーさんにレビューしてもらって下さい〜

2023-10-08 04:11 UTC, ochi-sho-private-study requested changes
一旦approve外す

2023-10-08 09:18 UTC, yuta-tokuda commented on backend/spec/factories/users.rb
> +    email { 'hogehoge@example.com' }
[修正不要]
出来るだけFakerというGemでランダムな値を定義した方が良いかもですー
今回は問題ないと思うんですけど、たまーにuniqカラムとかで他の人のテストデータと衝突してテスト落ちるみたいなこともあったりするので。

https://github.com/faker-ruby/faker

2023-10-08 09:18 UTC, yuta-tokuda commented on backend/spec/models/user_spec.rb
> +  it "有効な属性を持つ場合" do
[修正不要]
個人的には正常な動き以外(エラー)がちゃんと出るかどうかも重要視しているので、not nullのカラムが空の場合に保存されないかのテストがあった方が良いですねー

2023-10-08 09:20 UTC, yuta-tokuda commented
![LGTM](https://image.lgtmoon.dev/75135)

2023-10-08 09:20 UTC, merged