メモのdestroyするAPIを作成
Progaku-copy/progaku-archive pull request #29
Opened 2023-12-26 14:26 UTC by rikuya98

- closes #28 
## 対応内容
・メモのコントローラーに削除処理を追加
・routesにdestroyを追加
・削除機能のテストを追加

2024-01-02 09:17 UTC, ochi-sho-private-study requested changes
@rikuya98 
コメントしました！

2024-01-02 09:17 UTC, ochi-sho-private-study commented on backend/app/controllers/memos_controller.rb
> +    memo = Memo.find(params[:id])
今のままだと、memoが存在しなかったときに500になってしまうので、
findメソッドでレコードが存在しなかったときにraiseされる、
`ActiveRecord::RecordNotFound`クラスをrescueして、
404を返すようにしたいですね〜
（rescue_fromするともっと共通化できるけど、今はrescueでいいかなと思ってます。）

---

脳内でしか動作確認してないので、
動くか怪しいですが、以下のようなイメージです！
```ruby
def destroy
  memo = Memo.find(params[:id])
  memo.destroy
  head :no_content
rescue ActiveRecord::RecordNotFound => e
  render json: { message: e.message }, status: :not_found
end
```

2024-01-20 02:07 UTC, ochi-sho-private-study approved these changes
@rikuya98 
コメントしましたが、LGTMです！

2024-01-20 02:07 UTC, ochi-sho-private-study commented on backend/spec/requests/memos_spec.rb
> +          expect { delete '/memos/999' }.not_to change(Memo, :count)
idが999だと実際に存在していないかわかりづらいので、
以下のように存在し得ないidにしましょう！
```suggestion
          expect { delete '/memos/0' }.not_to change(Memo, :count)
```

2024-01-22 14:11 UTC, ochi-sho-private-study approved these changes
@rikuya98 
LGTM!

2024-01-23 04:45 UTC, yuta-tokuda commented
![LGTM](https://image.lgtmoon.dev/150785)

2024-01-23 04:45 UTC, merged